# Generated by Django 5.0.4 on 2024-05-08 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ssn', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('page', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('companyLogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companylogo')),
            ],
        ),
    ]
